# -*- coding: utf-8 -*-
"""jogoDaVelha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2M5Bt4x0-dvL7XYkug5mRAOvv-PvJRB
"""

pip install colorama

import os #limpar a tela
import random #utilização de números aleatórios
from colorama import Fore, Back, Style #formatação: cor do texto, cor de fundo e estilo da fonte

jogarNovamente = "s"
jogadas = 0
quemJoga = 2 #1 = CPU // 2 = jogador
maximoJogadas = 9
vit = "n"
tabuleiro = [
      [" ", " ", " "],
      [" ", " ", " "],
      [" ", " ", " "]
]

def tela():
  global tabuleiro
  global jogadas
  os.system('cls')
  print("    0   1   2")
  print("0:  " + tabuleiro[0][0] + " | " + tabuleiro[0][1] + " | " + tabuleiro[0][2])
  print("    -----------")
  print("1:  " + tabuleiro[1][0] + " | " + tabuleiro[1][1] + " | " + tabuleiro[1][2]) 
  print("    -----------")
  print("2:  " + tabuleiro[2][0] + " | " + tabuleiro[2][1] + " | " + tabuleiro[2][2])
  print("    -----------")
  print("Jogadas: " + Fore.GREEN + str(jogadas) + Fore.RESET)

def jogadorJoga():
  global jogadas
  global quemJoga
  global vit
  global maximoJogadas
  if quemJoga == 2 and jogadas < maximoJogadas:
    linha = int(input("Linha..: "))
    coluna = int(input("Coluna..: "))
    try:
      linha = int(input("Linha..: "))
      coluna = int(input("Coluna..: "))
      while tabuleiro[linha][coluna] != " ":
        linha = int(input("Linha..: "))
        coluna = int(input("Coluna..: "))
      tabuleiro[linha][coluna] = "X"
      quemJoga = 1
      jogadas += 1
    except:
      print("Jogada inválida! Tente novamente")
      os.system("pause")

def cpuJoga():
  global jogadas
  global quemJoga
  global vit
  global maximoJogadas
  if quemJoga == 1 and jogadas < maximoJogadas:
    linha = random.randrange(0,3)
    coluna = random.randrange(0,3)
    while tabuleiro[linha][coluna] != " ":
      linha = random.randrange(0,3)
      coluna = random.randrange(0,3)
    tabuleiro[linha][coluna] = "O"
    jogadas += 1
    quemJoga = 2

def verificaVitoria():
  global tabuleiro
  vitoria = "n"
  simbolos = ["X","O"]
  for s in simbolos:
    vitoria = "n"
    #verifica vitória em linhas
    indiceLinha = 0
    indiceColuna = 0
    while indiceLinha < 3:
      soma = 0
      indiceColuna = 0
      while indiceColuna < 3:
        if (tabuleiro[indiceLinha][indiceColuna] == s):
          soma += 1
        indiceColuna += 1
      if (soma == 3):
        vitoria = s
        break
      indiceLinha += 1
    if (vitoria != "n"):
      break

    #verifica vitória em colunas
    indiceLinha = 0
    indiceColuna = 0
    while indiceColuna < 3:
      soma = 0
      indiceLinha = 0
      while indiceLinha < 3:
        if (tabuleiro[indiceLinha][indiceColuna] == s):
          soma += 1
        indiceLinha += 1
      if (soma == 3):
        vitoria = s
        break
      indiceColuna += 1
    if (vitoria != "n"):
      break

    #verifica diagonal 1
    soma = 0
    indiceDiag = 0
    while indiceDiag < 3:
      if (tabuleiro[indiceDiag][indiceDiag] == s):
        soma += 1
      indiceDiag += 1
    if (soma == 3):
        vitoria = s
        break
    
    #verifica diagonal 2
    soma = 0
    indiceDiagL = 0
    indiceDiagC = 2
    while indiceDiagC >= 0:
      if (tabuleiro[indiceDiagL][indiceDiagC] == s):
        soma += 1
      indiceDiagL += 1
      indiceDiagC -= 1
    if (soma == 3):
        vitoria = s
        break
  return vitoria

def redefinir():
  global tabuleiro
  global jogadas
  global quemJoga
  global maximoJogadas
  global vit
  jogadas = 0
  quemJoga = 2 #1 = CPU // 2 = jogador
  maximoJogadas = 9
  vit = "n"
  tabuleiro = [
        [" ", " ", " "],
        [" ", " ", " "],
        [" ", " ", " "]
  ]

while (jogarNovamente == "s"):
  while True:
    tela()
    jogadorJoga()
    cpuJoga()
    tela()
    vit = verificaVitoria()
    if (vit != "n") or (jogadas > maximoJogadas):
      break
    
  print(Fore.RED + "Fim de jogo!" + Fore.YELLOW)
  if (vit == "X" or vit == "O"):
    print("Resultado: Jogador " + vit + " venceu!")
  else:
    print("Resultado: Empate, tente novamente!")
  jogarNovamente = input(Fore.BLUE + "Jogar novamente? [s/n]: " + Fore.RESET)
  redefinir()